### PR TITLE
More Composability

### PR DESCRIPTION
**Pull request by Magnitus-**
- Added environment variable to make fallback fetching of missing artifact dependencies from remote repos optional
- Moved most composable values to Dockerfile as environment variables
- Made expected names of all artifacts fully composable

### CODE REVIEW

**Comment by Magnitus-** [comment]
@DieterReuter Re-thinking about this pull request, I'm not 100% happy with it.

I think the change in the nature of the environment variables is good as it allows more composition in the artifact names (for example, in the project as it currently stands, a debian arm 64 bits root fs is assumed, but with my modification, you can override that to any root fs which makes sense).

For having environment variables in a config file vs having them in the Dockerfile, it depends on your view of the project I think (either as the master orchestration of the HypriotOS build in which case a config file makes sense or simply as the final step in the HypriotOS build in which case variables in the Dockerfile make more sense).

With my current modifications, however, it's 75% in the Dockerfile and 25% in the config file which suits my needs (all the environment variables I need are in the Dockerfile), but for maintainers, it just puts the config in two places. I could move the remaining variables from the config file to the Dockerfile, but it might be unsatisfying for those who view this project as a top-level orchestrator.

Instead, what I could do as a compromise is put the defaults back in the config file, but only set each environment variable in the config file ONLY if they aren't already defined in the running container (that way you can still pass select environment variable overrides to the build container at runtime).

Let me know what you think.

**Comment by DieterReuter** [comment]
I would prefer to have all the variable at a single place. For example, when I want to upgrade the os-rootfs, I have to change the version number in Dockerfile and the file checksum in version.config. 

Right now there are only 4-5 settings left in version.config, I think it's best to move them over to the Dockerfile. Then we'll have everything together and it's simple to change/update and makes maintaining way easier.

**Comment by Magnitus-** [comment]
Sounds good, I'll make the adjustment when I get back home.

**Comment by DieterReuter** [comment]
Thanks, this LGTM now!

**Pull request merged**
