### PR TITLE
Raspberry Pi 4 Support with upgrade to buster

### PR DESCRIPTION
**Pull request by lucashalbert**
Raspberry Pi 4 support added via sakaki-'s bcm2711 64-bit kernel.

Upgraded to buster release using new HypriotOS rootfs v2.2.1.

### CODE REVIEW

**Comment by asleeis** [comment]
Fantastic! I’ll be giving this a try this weekend. I was just about to try the steps to make the prior image work on the couple new RPi 4’s I got. Thank you!!

**Comment by aatchison** [comment]
Also stoked, may have to pick up a few more!

**Comment by lucashalbert** [comment]
Be aware that there seems to be an issue with cloud-init processing and applying the `/boot/user-data` file. The user "debian" is created on first boot without a password which means that you have to manually mount the filesystem on another system to copy a password hash to /etc/shadow.

I haven't had enough time to track down the origin of that problem at this time. If anyone else figures it out, please share.

**Comment by StefanScherer** [comment]
@lucashalbert This is awesome!

I tried to pick all relevant commits in the 32bit image-builder-rpi repo for updating to buster:
- https://github.com/hypriot/image-builder-rpi/commit/9dc8e1a966af0f719344b5c441325a9bdff15112, the `c_rehash` was relevant IIRC
- https://github.com/hypriot/image-builder-rpi/commit/57856fda6b38d885d36a63d664e24710c5e1a6ad

I've created #114 to switch to CircleCI to have build artifacts for PR's, so it would be easier to share the current status with the corresponding sd-card images. @DieterReuter PTAL

**Comment by jmatsushita** [comment]
Got it working here as well. And also figured out why the debian user was created as mentionned [here](https://github.com/DieterReuter/image-builder-rpi64/pull/113#issuecomment-541382480) by @lucashalbert 

The `image-builder-rpi` repo diverged a bit from this repo, in particular regarding how the user is created. Simply adding the `cloud.cfg` file from [`hypriot/image-builder-rpi`](https://github.com/hypriot/image-builder-rpi/blob/master/builder/files/etc/cloud/cloud.cfg) in `builder/files/etc/cloud` to this repo did the trick. 

The difference with the stock cloud.cfg are these [two lines for the `default_user` key](https://github.com/hypriot/image-builder-rpi/blob/master/builder/files/etc/cloud/cloud.cfg#L7-L8). 

@StefanScherer maybe it's time to provide these `arm64` images with the hypriot releases?

**Comment by lucashalbert** [comment]
Sorry for the lack of responses lately everyone. It's been a busy few months.

@StefanScherer, the switch to CircleCI was a great idea to break out each step of the build process and preserve all of the build artifacts.

The fixes that @jmatsushita has put together in PR #116 look very promising. I'm going to close this PR in favor of that one.

**Pull request closed without merging**
