### PR TITLE
Kernel 4.19.32 && Docker 18.09.3 et al.

### PR DESCRIPTION
**Pull request by argent-smith**
Here I propose the updates to our builder pipeline using my earlier proposed 4.19.32 kernel package and fresher Docker packages. Everything tested locally including running on RPi 3B.

### CODE REVIEW

**Comment by DieterReuter** [comment]
Hi @argent-smith, thanks for your contribution so far.

I'm currently upgrading all components for this HypriotOS/64bit for the RPi3 from the ground up. This will take some days of work, but in the end we should have all renewed and upgraded to the very latest versions.

I guess I will use some of your improvements from this PR and will double-check it and include all things into the next version of HypriotOS! As soon as I'm ready with the next version, I'm more than happy if you would help in testing it. Will keep you posted!

**Comment by DieterReuter** [comment]
I'll close this PR in favour of #106 where I'm installing the latest Docker Engine from the official APT repository from Docker. This enables us to stay in sync with all the later builds, then the user has just to initiate a "apt-get upgrade" and will get the latest Docker Engine version with all it's dependencies.

Thanks again for your contributions, some of your provided details helped me a lot to get to this new HypriotOS/arm64 release!

**Comment by argent-smith** [comment]
@DieterReuter thnx for evaluation. Looking forward to the updates ;)

**Comment by DieterReuter** [comment]
@argent-smith All updates already finished, new release is available for download. 😏

**Pull request closed without merging**
